# https://docs.codecov.com/docs/common-recipe-list
coverage:
  status:
    project:
      default:
        threshold: 1%  # the leniency in hitting the target
        informational: true
    patch:
      default:
        informational: true
