#!/bin/sh

for i in $*
do
        nom=`basename $i .internal.png`
	echo $i $nom	 $nom.internal.png
	montage  -geometry 256x192+5+5  -label "external view" $nom.external.png -label "camera view" $nom.internal.png $nom.jpg 
	convert $nom.jpg $nom.ppm
	rm -f $nom.jpg
echo
done
