.TH VISP 1

.SH NAME

visp-config \- get information about installed ViSP library.

.SH SYNOPSIS

.B visp-config [OPTIONS]

.SH DESCRIPTION

Provides information about ViSP library.

.SH OPTIONS

.TP 5
\-\-prefix
Show ViSP installation prefix.
.TP 5
\-\-cflags
Print pre-processor and compiler flags including third party
includes we depend on.
.TP 5
\-\-libs
Print library linking information with ViSP including third party
libraries we depend on.
.TP 5
\-\-version
Output ViSP information.
.TP 5
\-\-dumpversion
Output ViSP version information.
.TP 5
\-\-help
Show help message and exit.

.SH SEE ALSO

.TP
.B Home Page
http://www.irisa.fr/lagadic/visp

The primary starting point for learning about ViSP library.

.SH AUTHOR

Projet Lagadic / IRISA - Inria Rennes Bretagne Atlantique
