name: MacOS-ustk

# https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * SUN'

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    steps:
    # https://github.com/marketplace/actions/cancel-workflow-action
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print system information
      run: |
        sysctl -a | grep machdep.cpu
        sysctl -a | grep logical

    - name: Print OS information
      run: system_profiler SPSoftwareDataType

    - name: Install dependencies
      run: brew install libpng libjpeg libdc1394 opencv pcl librealsense zbar vtk fftw armadillo nlohmann-json

    - name: Clone visp-images
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      # https://remarkablemark.org/blog/2022/09/25/check-git-branch-exists-in-remote-repository/
      run: |
        git clone --depth 1 https://github.com/lagadic/visp-images ${HOME}/visp-images
        echo "VISP_INPUT_IMAGE_PATH=$HOME" >> $GITHUB_ENV
        echo ${VISP_INPUT_IMAGE_PATH}

    - name: Clone ustk-dataset
      run: |
        git clone --depth 1 https://github.com/lagadic/ustk-dataset ${HOME}/ustk-dataset
        echo "USTK_DATASET_PATH=$HOME/ustk-dataset" >> $GITHUB_ENV
        echo ${USTK_DATASET_PATH}

    - name: Clone ustk
      run: |
        git clone --depth 1 https://github.com/lagadic/ustk ${HOME}/ustk

    - name: Clone ustk-sample
      run: |
        git clone --depth 1 https://github.com/lagadic/ustk-sample ${HOME}/ustk-sample

    # Openblas location is exported explicitly because openblas is keg-only,
    # which means it was not symlinked into /usr/local/.
    # qt@5 is as a requested dependency for vtk and thus for pcl 1.12.1
    # qt@5 is keg-only, which means it was not symlinked into /usr/local that's why we need to set Qt5_DIR
    - name: Configure CMake
      run: |
        export LDFLAGS="-L/usr/local/opt/openblas/lib"
        export CPPFLAGS="-I/usr/local/opt/openblas/include"
        export Qt5_DIR="$(brew --prefix qt5)/lib/cmake/Qt5"
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/usr/local -DVISP_CONTRIB_MODULES_PATH=${HOME}/ustk/modules -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
        cat ViSP-third-party.txt

    - name: Compile
      working-directory: build
      run: make -j$(sysctl -n hw.logicalcpu) install

    - name: Run unit tests
      working-directory: build
      run: ctest -j$(sysctl -n hw.logicalcpu) --output-on-failure

    - name: ViSP + UsTK as 3rdparty with cmake
      run: |
        cd ${HOME}/ustk-sample
        mkdir ustk-sample-build
        cd ustk-sample-build
        cmake .. -DVISP_DIR=/tmp/usr/local/lib/cmake/visp
        make -j$(sysctl -n hw.logicalcpu)
